apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: jenkins
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      # Init container optional; rely on host sysctl done via minikube ssh
      containers:
        - name: sonarqube
          image: sonarqube:community
          # SonarQube is memory-hungry; adjust if you gave more to Minikube
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          ports:
            - name: web
              containerPort: 9000
          env:
            # JDBC integration with the Postgres service
            - name: SONAR_JDBC_URL
              value: "jdbc:postgresql://sonarqube-postgres.jenkins.svc.cluster.local:5432/sonarqube"
            - name: SONAR_JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sonarqube-db-secret
                  key: POSTGRES_USER
            - name: SONAR_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sonarqube-db-secret
                  key: POSTGRES_PASSWORD
            # Recommended to avoid mmap on some environments
            - name: SONAR_SEARCH_JAVAADDITIONALOPTS
              value: "-Dnode.store.allow_mmap=false"
          volumeMounts:
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data   # default data dir
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-data-pvc
