apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-postgres
  namespace: jenkins
  labels:
    app: sonarqube-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube-postgres
  template:
    metadata:
      labels:
        app: sonarqube-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          # Keep resources modest for local dev
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          envFrom:
            - secretRef:
                name: sonarqube-db-secret
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: sonarqube-postgres-pvc
